export enum TimeZones {
  "Africa/Abidjan",
  "Africa/Accra",
  "Africa/Addis_Ababa",
  "Africa/Algiers",
  "Africa/Asmera",
  "Africa/Bamako",
  "Africa/Bangui",
  "Africa/Banjul",
  "Africa/Bissau",
  "Africa/Blantyre",
  "Africa/Brazzaville",
  "Africa/Bujumbura",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Ceuta",
  "Africa/Conakry",
  "Africa/Dakar",
  "Africa/Dar_es_Salaam",
  "Africa/Djibouti",
  "Africa/Douala",
  "Africa/El_Aaiun",
  "Africa/Freetown",
  "Africa/Gaborone",
  "Africa/Harare",
  "Africa/Johannesburg",
  "Africa/Juba",
  "Africa/Kampala",
  "Africa/Khartoum",
  "Africa/Kigali",
  "Africa/Kinshasa",
  "Africa/Lagos",
  "Africa/Libreville",
  "Africa/Lome",
  "Africa/Luanda",
  "Africa/Lubumbashi",
  "Africa/Lusaka",
  "Africa/Malabo",
  "Africa/Maputo",
  "Africa/Maseru",
  "Africa/Mbabane",
  "Africa/Mogadishu",
  "Africa/Monrovia",
  "Africa/Nairobi",
  "Africa/Ndjamena",
  "Africa/Niamey",
  "Africa/Nouakchott",
  "Africa/Ouagadougou",
  "Africa/Porto-Novo",
  "Africa/Sao_Tome",
  "Africa/Tripoli",
  "Africa/Tunis",
  "Africa/Windhoek",
  "America/Adak",
  "America/Anchorage",
  "America/Anguilla",
  "America/Antigua",
  "America/Araguaina",
  "America/Argentina/La_Rioja",
  "America/Argentina/Rio_Gallegos",
  "America/Argentina/Salta",
  "America/Argentina/San_Juan",
  "America/Argentina/San_Luis",
  "America/Argentina/Tucuman",
  "America/Argentina/Ushuaia",
  "America/Aruba",
  "America/Asuncion",
  "America/Bahia",
  "America/Bahia_Banderas",
  "America/Barbados",
  "America/Belem",
  "America/Belize",
  "America/Blanc-Sablon",
  "America/Boa_Vista",
  "America/Bogota",
  "America/Boise",
  "America/Buenos_Aires",
  "America/Cambridge_Bay",
  "America/Campo_Grande",
  "America/Cancun",
  "America/Caracas",
  "America/Catamarca",
  "America/Cayenne",
  "America/Cayman",
  "America/Chicago",
  "America/Chihuahua",
  "America/Coral_Harbour",
  "America/Cordoba",
  "America/Costa_Rica",
  "America/Creston",
  "America/Cuiaba",
  "America/Curacao",
  "America/Danmarkshavn",
  "America/Dawson",
  "America/Dawson_Creek",
  "America/Denver",
  "America/Detroit",
  "America/Dominica",
  "America/Edmonton",
  "America/Eirunepe",
  "America/El_Salvador",
  "America/Fort_Nelson",
  "America/Fortaleza",
  "America/Glace_Bay",
  "America/Godthab",
  "America/Goose_Bay",
  "America/Grand_Turk",
  "America/Grenada",
  "America/Guadeloupe",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Guyana",
  "America/Halifax",
  "America/Havana",
  "America/Hermosillo",
  "America/Indiana/Knox",
  "America/Indiana/Marengo",
  "America/Indiana/Petersburg",
  "America/Indiana/Tell_City",
  "America/Indiana/Vevay",
  "America/Indiana/Vincennes",
  "America/Indiana/Winamac",
  "America/Indianapolis",
  "America/Inuvik",
  "America/Iqaluit",
  "America/Jamaica",
  "America/Jujuy",
  "America/Juneau",
  "America/Kentucky/Monticello",
  "America/Kralendijk",
  "America/La_Paz",
  "America/Lima",
  "America/Los_Angeles",
  "America/Louisville",
  "America/Lower_Princes",
  "America/Maceio",
  "America/Managua",
  "America/Manaus",
  "America/Marigot",
  "America/Martinique",
  "America/Matamoros",
  "America/Mazatlan",
  "America/Mendoza",
  "America/Menominee",
  "America/Merida",
  "America/Metlakatla",
  "America/Mexico_City",
  "America/Miquelon",
  "America/Moncton",
  "America/Monterrey",
  "America/Montevideo",
  "America/Montreal",
  "America/Montserrat",
  "America/Nassau",
  "America/New_York",
  "America/Nipigon",
  "America/Nome",
  "America/Noronha",
  "America/North_Dakota/Beulah",
  "America/North_Dakota/Center",
  "America/North_Dakota/New_Salem",
  "America/Ojinaga",
  "America/Panama",
  "America/Pangnirtung",
  "America/Paramaribo",
  "America/Phoenix",
  "America/Port-au-Prince",
  "America/Port_of_Spain",
  "America/Porto_Velho",
  "America/Puerto_Rico",
  "America/Punta_Arenas",
  "America/Rainy_River",
  "America/Rankin_Inlet",
  "America/Recife",
  "America/Regina",
  "America/Resolute",
  "America/Rio_Branco",
  "America/Santa_Isabel",
  "America/Santarem",
  "America/Santiago",
  "America/Santo_Domingo",
  "America/Sao_Paulo",
  "America/Scoresbysund",
  "America/Sitka",
  "America/St_Barthelemy",
  "America/St_Johns",
  "America/St_Kitts",
  "America/St_Lucia",
  "America/St_Thomas",
  "America/St_Vincent",
  "America/Swift_Current",
  "America/Tegucigalpa",
  "America/Thule",
  "America/Thunder_Bay",
  "America/Tijuana",
  "America/Toronto",
  "America/Tortola",
  "America/Vancouver",
  "America/Whitehorse",
  "America/Winnipeg",
  "America/Yakutat",
  "America/Yellowknife",
  "Antarctica/Casey",
  "Antarctica/Davis",
  "Antarctica/DumontDUrville",
  "Antarctica/Macquarie",
  "Antarctica/Mawson",
  "Antarctica/McMurdo",
  "Antarctica/Palmer",
  "Antarctica/Rothera",
  "Antarctica/Syowa",
  "Antarctica/Troll",
  "Antarctica/Vostok",
  "Arctic/Longyearbyen",
  "Asia/Aden",
  "Asia/Almaty",
  "Asia/Amman",
  "Asia/Anadyr",
  "Asia/Aqtau",
  "Asia/Aqtobe",
  "Asia/Ashgabat",
  "Asia/Atyrau",
  "Asia/Baghdad",
  "Asia/Bahrain",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Barnaul",
  "Asia/Beirut",
  "Asia/Bishkek",
  "Asia/Brunei",
  "Asia/Calcutta",
  "Asia/Chita",
  "Asia/Choibalsan",
  "Asia/Colombo",
  "Asia/Damascus",
  "Asia/Dhaka",
  "Asia/Dili",
  "Asia/Dubai",
  "Asia/Dushanbe",
  "Asia/Famagusta",
  "Asia/Gaza",
  "Asia/Hebron",
  "Asia/Hong_Kong",
  "Asia/Hovd",
  "Asia/Irkutsk",
  "Asia/Jakarta",
  "Asia/Jayapura",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Kamchatka",
  "Asia/Karachi",
  "Asia/Katmandu",
  "Asia/Khandyga",
  "Asia/Krasnoyarsk",
  "Asia/Kuala_Lumpur",
  "Asia/Kuching",
  "Asia/Kuwait",
  "Asia/Macau",
  "Asia/Magadan",
  "Asia/Makassar",
  "Asia/Manila",
  "Asia/Muscat",
  "Asia/Nicosia",
  "Asia/Novokuznetsk",
  "Asia/Novosibirsk",
  "Asia/Omsk",
  "Asia/Oral",
  "Asia/Phnom_Penh",
  "Asia/Pontianak",
  "Asia/Pyongyang",
  "Asia/Qatar",
  "Asia/Qostanay",
  "Asia/Qyzylorda",
  "Asia/Rangoon",
  "Asia/Riyadh",
  "Asia/Saigon",
  "Asia/Sakhalin",
  "Asia/Samarkand",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Srednekolymsk",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Thimphu",
  "Asia/Tokyo",
  "Asia/Tomsk",
  "Asia/Ulaanbaatar",
  "Asia/Urumqi",
  "Asia/Ust-Nera",
  "Asia/Vientiane",
  "Asia/Vladivostok",
  "Asia/Yakutsk",
  "Asia/Yekaterinburg",
  "Asia/Yerevan",
  "Atlantic/Azores",
  "Atlantic/Bermuda",
  "Atlantic/Canary",
  "Atlantic/Cape_Verde",
  "Atlantic/Faeroe",
  "Atlantic/Madeira",
  "Atlantic/Reykjavik",
  "Atlantic/South_Georgia",
  "Atlantic/St_Helena",
  "Atlantic/Stanley",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Broken_Hill",
  "Australia/Currie",
  "Australia/Darwin",
  "Australia/Eucla",
  "Australia/Hobart",
  "Australia/Lindeman",
  "Australia/Lord_Howe",
  "Australia/Melbourne",
  "Australia/Perth",
  "Australia/Sydney",
  "Europe/Amsterdam",
  "Europe/Andorra",
  "Europe/Astrakhan",
  "Europe/Athens",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Bratislava",
  "Europe/Brussels",
  "Europe/Bucharest",
  "Europe/Budapest",
  "Europe/Busingen",
  "Europe/Chisinau",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Gibraltar",
  "Europe/Guernsey",
  "Europe/Helsinki",
  "Europe/Isle_of_Man",
  "Europe/Istanbul",
  "Europe/Jersey",
  "Europe/Kaliningrad",
  "Europe/Kiev",
  "Europe/Kirov",
  "Europe/Lisbon",
  "Europe/Ljubljana",
  "Europe/London",
  "Europe/Luxembourg",
  "Europe/Madrid",
  "Europe/Malta",
  "Europe/Mariehamn",
  "Europe/Minsk",
  "Europe/Monaco",
  "Europe/Moscow",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Podgorica",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/Samara",
  "Europe/San_Marino",
  "Europe/Sarajevo",
  "Europe/Saratov",
  "Europe/Simferopol",
  "Europe/Skopje",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Tirane",
  "Europe/Ulyanovsk",
  "Europe/Uzhgorod",
  "Europe/Vaduz",
  "Europe/Vatican",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Volgograd",
  "Europe/Warsaw",
  "Europe/Zagreb",
  "Europe/Zaporozhye",
  "Europe/Zurich",
  "Indian/Antananarivo",
  "Indian/Chagos",
  "Indian/Christmas",
  "Indian/Cocos",
  "Indian/Comoro",
  "Indian/Kerguelen",
  "Indian/Mahe",
  "Indian/Maldives",
  "Indian/Mauritius",
  "Indian/Mayotte",
  "Indian/Reunion",
  "Pacific/Apia",
  "Pacific/Auckland",
  "Pacific/Bougainville",
  "Pacific/Chatham",
  "Pacific/Easter",
  "Pacific/Efate",
  "Pacific/Enderbury",
  "Pacific/Fakaofo",
  "Pacific/Fiji",
  "Pacific/Funafuti",
  "Pacific/Galapagos",
  "Pacific/Gambier",
  "Pacific/Guadalcanal",
  "Pacific/Guam",
  "Pacific/Honolulu",
  "Pacific/Johnston",
  "Pacific/Kiritimati",
  "Pacific/Kosrae",
  "Pacific/Kwajalein",
  "Pacific/Majuro",
  "Pacific/Marquesas",
  "Pacific/Midway",
  "Pacific/Nauru",
  "Pacific/Niue",
  "Pacific/Norfolk",
  "Pacific/Noumea",
  "Pacific/Pago_Pago",
  "Pacific/Palau",
  "Pacific/Pitcairn",
  "Pacific/Ponape",
  "Pacific/Port_Moresby",
  "Pacific/Rarotonga",
  "Pacific/Saipan",
  "Pacific/Tahiti",
  "Pacific/Tarawa",
  "Pacific/Tongatapu",
  "Pacific/Truk",
  "Pacific/Wake",
  "Pacific/Wallis",
}


export const timeZoneValues: Record<TimeZones, string> = {
  [TimeZones["Africa/Abidjan"]]: "Africa/Abidjan",
  [TimeZones["Africa/Accra"]]: "Africa/Accra",
  [TimeZones["Africa/Addis_Ababa"]]: "Africa/Addis_Ababa",
  [TimeZones["Africa/Algiers"]]: "Africa/Algiers",
  [TimeZones["Africa/Asmera"]]: "Africa/Asmera",
  [TimeZones["Africa/Bamako"]]: "Africa/Bamako",
  [TimeZones["Africa/Bangui"]]: "Africa/Bangui",
  [TimeZones["Africa/Banjul"]]: "Africa/Banjul",
  [TimeZones["Africa/Bissau"]]: "Africa/Bissau",
  [TimeZones["Africa/Blantyre"]]: "Africa/Blantyre",
  [TimeZones["Africa/Brazzaville"]]: "Africa/Brazzaville",
  [TimeZones["Africa/Bujumbura"]]: "Africa/Bujumbura",
  [TimeZones["Africa/Cairo"]]: "Africa/Cairo",
  [TimeZones["Africa/Casablanca"]]: "Africa/Casablanca",
  [TimeZones["Africa/Ceuta"]]: "Africa/Ceuta",
  [TimeZones["Africa/Conakry"]]: "Africa/Conakry",
  [TimeZones["Africa/Dakar"]]: "Africa/Dakar",
  [TimeZones["Africa/Dar_es_Salaam"]]: "Africa/Dar_es_Salaam",
  [TimeZones["Africa/Djibouti"]]: "Africa/Djibouti",
  [TimeZones["Africa/Douala"]]: "Africa/Douala",
  [TimeZones["Africa/El_Aaiun"]]: "Africa/El_Aaiun",
  [TimeZones["Africa/Freetown"]]: "Africa/Freetown",
  [TimeZones["Africa/Gaborone"]]: "Africa/Gaborone",
  [TimeZones["Africa/Harare"]]: "Africa/Harare",
  [TimeZones["Africa/Johannesburg"]]: "Africa/Johannesburg",
  [TimeZones["Africa/Juba"]]: "Africa/Juba",
  [TimeZones["Africa/Kampala"]]: "Africa/Kampala",
  [TimeZones["Africa/Khartoum"]]: "Africa/Khartoum",
  [TimeZones["Africa/Kigali"]]: "Africa/Kigali",
  [TimeZones["Africa/Kinshasa"]]: "Africa/Kinshasa",
  [TimeZones["Africa/Lagos"]]: "Africa/Lagos",
  [TimeZones["Africa/Libreville"]]: "Africa/Libreville",
  [TimeZones["Africa/Lome"]]: "Africa/Lome",
  [TimeZones["Africa/Luanda"]]: "Africa/Luanda",
  [TimeZones["Africa/Lubumbashi"]]: "Africa/Lubumbashi",
  [TimeZones["Africa/Lusaka"]]: "Africa/Lusaka",
  [TimeZones["Africa/Malabo"]]: "Africa/Malabo",
  [TimeZones["Africa/Maputo"]]: "Africa/Maputo",
  [TimeZones["Africa/Maseru"]]: "Africa/Maseru",
  [TimeZones["Africa/Mbabane"]]: "Africa/Mbabane",
  [TimeZones["Africa/Mogadishu"]]: "Africa/Mogadishu",
  [TimeZones["Africa/Monrovia"]]: "Africa/Monrovia",
  [TimeZones["Africa/Nairobi"]]: "Africa/Nairobi",
  [TimeZones["Africa/Ndjamena"]]: "Africa/Ndjamena",
  [TimeZones["Africa/Niamey"]]: "Africa/Niamey",
  [TimeZones["Africa/Nouakchott"]]: "Africa/Nouakchott",
  [TimeZones["Africa/Ouagadougou"]]: "Africa/Ouagadougou",
  [TimeZones["Africa/Porto-Novo"]]: "Africa/Porto-Novo",
  [TimeZones["Africa/Sao_Tome"]]: "Africa/Sao_Tome",
  [TimeZones["Africa/Tripoli"]]: "Africa/Tripoli",
  [TimeZones["Africa/Tunis"]]: "Africa/Tunis",
  [TimeZones["Africa/Windhoek"]]: "Africa/Windhoek",
  [TimeZones["America/Adak"]]: "America/Adak",
  [TimeZones["America/Anchorage"]]: "America/Anchorage",
  [TimeZones["America/Anguilla"]]: "America/Anguilla",
  [TimeZones["America/Antigua"]]: "America/Antigua",
  [TimeZones["America/Araguaina"]]: "America/Araguaina",
  [TimeZones["America/Argentina/La_Rioja"]]: "America/Argentina/La_Rioja",
  [TimeZones["America/Argentina/Rio_Gallegos"]]: "America/Argentina/Rio_Gallegos",
  [TimeZones["America/Argentina/Salta"]]: "America/Argentina/Salta",
  [TimeZones["America/Argentina/San_Juan"]]: "America/Argentina/San_Juan",
  [TimeZones["America/Argentina/San_Luis"]]: "America/Argentina/San_Luis",
  [TimeZones["America/Argentina/Tucuman"]]: "America/Argentina/Tucuman",
  [TimeZones["America/Argentina/Ushuaia"]]: "America/Argentina/Ushuaia",
  [TimeZones["America/Aruba"]]: "America/Aruba",
  [TimeZones["America/Asuncion"]]: "America/Asuncion",
  [TimeZones["America/Bahia"]]: "America/Bahia",
  [TimeZones["America/Bahia_Banderas"]]: "America/Bahia_Banderas",
  [TimeZones["America/Barbados"]]: "America/Barbados",
  [TimeZones["America/Belem"]]: "America/Belem",
  [TimeZones["America/Belize"]]: "America/Belize",
  [TimeZones["America/Blanc-Sablon"]]: "America/Blanc-Sablon",
  [TimeZones["America/Boa_Vista"]]: "America/Boa_Vista",
  [TimeZones["America/Bogota"]]: "America/Bogota",
  [TimeZones["America/Boise"]]: "America/Boise",
  [TimeZones["America/Buenos_Aires"]]: "America/Buenos_Aires",
  [TimeZones["America/Cambridge_Bay"]]: "America/Cambridge_Bay",
  [TimeZones["America/Campo_Grande"]]: "America/Campo_Grande",
  [TimeZones["America/Cancun"]]: "America/Cancun",
  [TimeZones["America/Caracas"]]: "America/Caracas",
  [TimeZones["America/Catamarca"]]: "America/Catamarca",
  [TimeZones["America/Cayenne"]]: "America/Cayenne",
  [TimeZones["America/Cayman"]]: "America/Cayman",
  [TimeZones["America/Chicago"]]: "America/Chicago",
  [TimeZones["America/Chihuahua"]]: "America/Chihuahua",
  [TimeZones["America/Coral_Harbour"]]: "America/Coral_Harbour",
  [TimeZones["America/Cordoba"]]: "America/Cordoba",
  [TimeZones["America/Costa_Rica"]]: "America/Costa_Rica",
  [TimeZones["America/Creston"]]: "America/Creston",
  [TimeZones["America/Cuiaba"]]: "America/Cuiaba",
  [TimeZones["America/Curacao"]]: "America/Curacao",
  [TimeZones["America/Danmarkshavn"]]: "America/Danmarkshavn",
  [TimeZones["America/Dawson"]]: "America/Dawson",
  [TimeZones["America/Dawson_Creek"]]: "America/Dawson_Creek",
  [TimeZones["America/Denver"]]: "America/Denver",
  [TimeZones["America/Detroit"]]: "America/Detroit",
  [TimeZones["America/Dominica"]]: "America/Dominica",
  [TimeZones["America/Edmonton"]]: "America/Edmonton",
  [TimeZones["America/Eirunepe"]]: "America/Eirunepe",
  [TimeZones["America/El_Salvador"]]: "America/El_Salvador",
  [TimeZones["America/Fort_Nelson"]]: "America/Fort_Nelson",
  [TimeZones["America/Fortaleza"]]: "America/Fortaleza",
  [TimeZones["America/Glace_Bay"]]: "America/Glace_Bay",
  [TimeZones["America/Godthab"]]: "America/Godthab",
  [TimeZones["America/Goose_Bay"]]: "America/Goose_Bay",
  [TimeZones["America/Grand_Turk"]]: "America/Grand_Turk",
  [TimeZones["America/Grenada"]]: "America/Grenada",
  [TimeZones["America/Guadeloupe"]]: "America/Guadeloupe",
  [TimeZones["America/Guatemala"]]: "America/Guatemala",
  [TimeZones["America/Guayaquil"]]: "America/Guayaquil",
  [TimeZones["America/Guyana"]]: "America/Guyana",
  [TimeZones["America/Halifax"]]: "America/Halifax",
  [TimeZones["America/Havana"]]: "America/Havana",
  [TimeZones["America/Hermosillo"]]: "America/Hermosillo",
  [TimeZones["America/Indiana/Knox"]]: "America/Indiana/Knox",
  [TimeZones["America/Indiana/Marengo"]]: "America/Indiana/Marengo",
  [TimeZones["America/Indiana/Petersburg"]]: "America/Indiana/Petersburg",
  [TimeZones["America/Indiana/Tell_City"]]: "America/Indiana/Tell_City",
  [TimeZones["America/Indiana/Vevay"]]: "America/Indiana/Vevay",
  [TimeZones["America/Indiana/Vincennes"]]: "America/Indiana/Vincennes",
  [TimeZones["America/Indiana/Winamac"]]: "America/Indiana/Winamac",
  [TimeZones["America/Indianapolis"]]: "America/Indianapolis",
  [TimeZones["America/Inuvik"]]: "America/Inuvik",
  [TimeZones["America/Iqaluit"]]: "America/Iqaluit",
  [TimeZones["America/Jamaica"]]: "America/Jamaica",
  [TimeZones["America/Jujuy"]]: "America/Jujuy",
  [TimeZones["America/Juneau"]]: "America/Juneau",
  [TimeZones["America/Kentucky/Monticello"]]: "America/Kentucky/Monticello",
  [TimeZones["America/Kralendijk"]]: "America/Kralendijk",
  [TimeZones["America/La_Paz"]]: "America/La_Paz",
  [TimeZones["America/Lima"]]: "America/Lima",
  [TimeZones["America/Los_Angeles"]]: "America/Los_Angeles",
  [TimeZones["America/Louisville"]]: "America/Louisville",
  [TimeZones["America/Lower_Princes"]]: "America/Lower_Princes",
  [TimeZones["America/Maceio"]]: "America/Maceio",
  [TimeZones["America/Managua"]]: "America/Managua",
  [TimeZones["America/Manaus"]]: "America/Manaus",
  [TimeZones["America/Marigot"]]: "America/Marigot",
  [TimeZones["America/Martinique"]]: "America/Martinique",
  [TimeZones["America/Matamoros"]]: "America/Matamoros",
  [TimeZones["America/Mazatlan"]]: "America/Mazatlan",
  [TimeZones["America/Mendoza"]]: "America/Mendoza",
  [TimeZones["America/Menominee"]]: "America/Menominee",
  [TimeZones["America/Merida"]]: "America/Merida",
  [TimeZones["America/Metlakatla"]]: "America/Metlakatla",
  [TimeZones["America/Mexico_City"]]: "America/Mexico_City",
  [TimeZones["America/Miquelon"]]: "America/Miquelon",
  [TimeZones["America/Moncton"]]: "America/Moncton",
  [TimeZones["America/Monterrey"]]: "America/Monterrey",
  [TimeZones["America/Montevideo"]]: "America/Montevideo",
  [TimeZones["America/Montreal"]]: "America/Montreal",
  [TimeZones["America/Montserrat"]]: "America/Montserrat",
  [TimeZones["America/Nassau"]]: "America/Nassau",
  [TimeZones["America/New_York"]]: "America/New_York",
  [TimeZones["America/Nipigon"]]: "America/Nipigon",
  [TimeZones["America/Nome"]]: "America/Nome",
  [TimeZones["America/Noronha"]]: "America/Noronha",
  [TimeZones["America/North_Dakota/Beulah"]]: "America/North_Dakota/Beulah",
  [TimeZones["America/North_Dakota/Center"]]: "America/North_Dakota/Center",
  [TimeZones["America/North_Dakota/New_Salem"]]: "America/North_Dakota/New_Salem",
  [TimeZones["America/Ojinaga"]]: "America/Ojinaga",
  [TimeZones["America/Panama"]]: "America/Panama",
  [TimeZones["America/Pangnirtung"]]: "America/Pangnirtung",
  [TimeZones["America/Paramaribo"]]: "America/Paramaribo",
  [TimeZones["America/Phoenix"]]: "America/Phoenix",
  [TimeZones["America/Port-au-Prince"]]: "America/Port-au-Prince",
  [TimeZones["America/Port_of_Spain"]]: "America/Port_of_Spain",
  [TimeZones["America/Porto_Velho"]]: "America/Porto_Velho",
  [TimeZones["America/Puerto_Rico"]]: "America/Puerto_Rico",
  [TimeZones["America/Punta_Arenas"]]: "America/Punta_Arenas",
  [TimeZones["America/Rainy_River"]]: "America/Rainy_River",
  [TimeZones["America/Rankin_Inlet"]]: "America/Rankin_Inlet",
  [TimeZones["America/Recife"]]: "America/Recife",
  [TimeZones["America/Regina"]]: "America/Regina",
  [TimeZones["America/Resolute"]]: "America/Resolute",
  [TimeZones["America/Rio_Branco"]]: "America/Rio_Branco",
  [TimeZones["America/Santa_Isabel"]]: "America/Santa_Isabel",
  [TimeZones["America/Santarem"]]: "America/Santarem",
  [TimeZones["America/Santiago"]]: "America/Santiago",
  [TimeZones["America/Santo_Domingo"]]: "America/Santo_Domingo",
  [TimeZones["America/Sao_Paulo"]]: "America/Sao_Paulo",
  [TimeZones["America/Scoresbysund"]]: "America/Scoresbysund",
  [TimeZones["America/Sitka"]]: "America/Sitka",
  [TimeZones["America/St_Barthelemy"]]: "America/St_Barthelemy",
  [TimeZones["America/St_Johns"]]: "America/St_Johns",
  [TimeZones["America/St_Kitts"]]: "America/St_Kitts",
  [TimeZones["America/St_Lucia"]]: "America/St_Lucia",
  [TimeZones["America/St_Thomas"]]: "America/St_Thomas",
  [TimeZones["America/St_Vincent"]]: "America/St_Vincent",
  [TimeZones["America/Swift_Current"]]: "America/Swift_Current",
  [TimeZones["America/Tegucigalpa"]]: "America/Tegucigalpa",
  [TimeZones["America/Thule"]]: "America/Thule",
  [TimeZones["America/Thunder_Bay"]]: "America/Thunder_Bay",
  [TimeZones["America/Tijuana"]]: "America/Tijuana",
  [TimeZones["America/Toronto"]]: "America/Toronto",
  [TimeZones["America/Tortola"]]: "America/Tortola",
  [TimeZones["America/Vancouver"]]: "America/Vancouver",
  [TimeZones["America/Whitehorse"]]: "America/Whitehorse",
  [TimeZones["America/Winnipeg"]]: "America/Winnipeg",
  [TimeZones["America/Yakutat"]]: "America/Yakutat",
  [TimeZones["America/Yellowknife"]]: "America/Yellowknife",
  [TimeZones["Antarctica/Casey"]]: "Antarctica/Casey",
  [TimeZones["Antarctica/Davis"]]: "Antarctica/Davis",
  [TimeZones["Antarctica/DumontDUrville"]]: "Antarctica/DumontDUrville",
  [TimeZones["Antarctica/Macquarie"]]: "Antarctica/Macquarie",
  [TimeZones["Antarctica/Mawson"]]: "Antarctica/Mawson",
  [TimeZones["Antarctica/McMurdo"]]: "Antarctica/McMurdo",
  [TimeZones["Antarctica/Palmer"]]: "Antarctica/Palmer",
  [TimeZones["Antarctica/Rothera"]]: "Antarctica/Rothera",
  [TimeZones["Antarctica/Syowa"]]: "Antarctica/Syowa",
  [TimeZones["Antarctica/Troll"]]: "Antarctica/Troll",
  [TimeZones["Antarctica/Vostok"]]: "Antarctica/Vostok",
  [TimeZones["Arctic/Longyearbyen"]]: "Arctic/Longyearbyen",
  [TimeZones["Asia/Aden"]]: "Asia/Aden",
  [TimeZones["Asia/Almaty"]]: "Asia/Almaty",
  [TimeZones["Asia/Amman"]]: "Asia/Amman",
  [TimeZones["Asia/Anadyr"]]: "Asia/Anadyr",
  [TimeZones["Asia/Aqtau"]]: "Asia/Aqtau",
  [TimeZones["Asia/Aqtobe"]]: "Asia/Aqtobe",
  [TimeZones["Asia/Ashgabat"]]: "Asia/Ashgabat",
  [TimeZones["Asia/Atyrau"]]: "Asia/Atyrau",
  [TimeZones["Asia/Baghdad"]]: "Asia/Baghdad",
  [TimeZones["Asia/Bahrain"]]: "Asia/Bahrain",
  [TimeZones["Asia/Baku"]]: "Asia/Baku",
  [TimeZones["Asia/Bangkok"]]: "Asia/Bangkok",
  [TimeZones["Asia/Barnaul"]]: "Asia/Barnaul",
  [TimeZones["Asia/Beirut"]]: "Asia/Beirut",
  [TimeZones["Asia/Bishkek"]]: "Asia/Bishkek",
  [TimeZones["Asia/Brunei"]]: "Asia/Brunei",
  [TimeZones["Asia/Calcutta"]]: "Asia/Calcutta",
  [TimeZones["Asia/Chita"]]: "Asia/Chita",
  [TimeZones["Asia/Choibalsan"]]: "Asia/Choibalsan",
  [TimeZones["Asia/Colombo"]]: "Asia/Colombo",
  [TimeZones["Asia/Damascus"]]: "Asia/Damascus",
  [TimeZones["Asia/Dhaka"]]: "Asia/Dhaka",
  [TimeZones["Asia/Dili"]]: "Asia/Dili",
  [TimeZones["Asia/Dubai"]]: "Asia/Dubai",
  [TimeZones["Asia/Dushanbe"]]: "Asia/Dushanbe",
  [TimeZones["Asia/Famagusta"]]: "Asia/Famagusta",
  [TimeZones["Asia/Gaza"]]: "Asia/Gaza",
  [TimeZones["Asia/Hebron"]]: "Asia/Hebron",
  [TimeZones["Asia/Hong_Kong"]]: "Asia/Hong_Kong",
  [TimeZones["Asia/Hovd"]]: "Asia/Hovd",
  [TimeZones["Asia/Irkutsk"]]: "Asia/Irkutsk",
  [TimeZones["Asia/Jakarta"]]: "Asia/Jakarta",
  [TimeZones["Asia/Jayapura"]]: "Asia/Jayapura",
  [TimeZones["Asia/Jerusalem"]]: "Asia/Jerusalem",
  [TimeZones["Asia/Kabul"]]: "Asia/Kabul",
  [TimeZones["Asia/Kamchatka"]]: "Asia/Kamchatka",
  [TimeZones["Asia/Karachi"]]: "Asia/Karachi",
  [TimeZones["Asia/Katmandu"]]: "Asia/Katmandu",
  [TimeZones["Asia/Khandyga"]]: "Asia/Khandyga",
  [TimeZones["Asia/Krasnoyarsk"]]: "Asia/Krasnoyarsk",
  [TimeZones["Asia/Kuala_Lumpur"]]: "Asia/Kuala_Lumpur",
  [TimeZones["Asia/Kuching"]]: "Asia/Kuching",
  [TimeZones["Asia/Kuwait"]]: "Asia/Kuwait",
  [TimeZones["Asia/Macau"]]: "Asia/Macau",
  [TimeZones["Asia/Magadan"]]: "Asia/Magadan",
  [TimeZones["Asia/Makassar"]]: "Asia/Makassar",
  [TimeZones["Asia/Manila"]]: "Asia/Manila",
  [TimeZones["Asia/Muscat"]]: "Asia/Muscat",
  [TimeZones["Asia/Nicosia"]]: "Asia/Nicosia",
  [TimeZones["Asia/Novokuznetsk"]]: "Asia/Novokuznetsk",
  [TimeZones["Asia/Novosibirsk"]]: "Asia/Novosibirsk",
  [TimeZones["Asia/Omsk"]]: "Asia/Omsk",
  [TimeZones["Asia/Oral"]]: "Asia/Oral",
  [TimeZones["Asia/Phnom_Penh"]]: "Asia/Phnom_Penh",
  [TimeZones["Asia/Pontianak"]]: "Asia/Pontianak",
  [TimeZones["Asia/Pyongyang"]]: "Asia/Pyongyang",
  [TimeZones["Asia/Qatar"]]: "Asia/Qatar",
  [TimeZones["Asia/Qostanay"]]: "Asia/Qostanay",
  [TimeZones["Asia/Qyzylorda"]]: "Asia/Qyzylorda",
  [TimeZones["Asia/Rangoon"]]: "Asia/Rangoon",
  [TimeZones["Asia/Riyadh"]]: "Asia/Riyadh",
  [TimeZones["Asia/Saigon"]]: "Asia/Saigon",
  [TimeZones["Asia/Sakhalin"]]: "Asia/Sakhalin",
  [TimeZones["Asia/Samarkand"]]: "Asia/Samarkand",
  [TimeZones["Asia/Seoul"]]: "Asia/Seoul",
  [TimeZones["Asia/Shanghai"]]: "Asia/Shanghai",
  [TimeZones["Asia/Singapore"]]: "Asia/Singapore",
  [TimeZones["Asia/Srednekolymsk"]]: "Asia/Srednekolymsk",
  [TimeZones["Asia/Taipei"]]: "Asia/Taipei",
  [TimeZones["Asia/Tashkent"]]: "Asia/Tashkent",
  [TimeZones["Asia/Tbilisi"]]: "Asia/Tbilisi",
  [TimeZones["Asia/Tehran"]]: "Asia/Tehran",
  [TimeZones["Asia/Thimphu"]]: "Asia/Thimphu",
  [TimeZones["Asia/Tokyo"]]: "Asia/Tokyo",
  [TimeZones["Asia/Tomsk"]]: "Asia/Tomsk",
  [TimeZones["Asia/Ulaanbaatar"]]: "Asia/Ulaanbaatar",
  [TimeZones["Asia/Urumqi"]]: "Asia/Urumqi",
  [TimeZones["Asia/Ust-Nera"]]: "Asia/Ust-Nera",
  [TimeZones["Asia/Vientiane"]]: "Asia/Vientiane",
  [TimeZones["Asia/Vladivostok"]]: "Asia/Vladivostok",
  [TimeZones["Asia/Yakutsk"]]: "Asia/Yakutsk",
  [TimeZones["Asia/Yekaterinburg"]]: "Asia/Yekaterinburg",
  [TimeZones["Asia/Yerevan"]]: "Asia/Yerevan",
  [TimeZones["Atlantic/Azores"]]: "Atlantic/Azores",
  [TimeZones["Atlantic/Bermuda"]]: "Atlantic/Bermuda",
  [TimeZones["Atlantic/Canary"]]: "Atlantic/Canary",
  [TimeZones["Atlantic/Cape_Verde"]]: "Atlantic/Cape_Verde",
  [TimeZones["Atlantic/Faeroe"]]: "Atlantic/Faeroe",
  [TimeZones["Atlantic/Madeira"]]: "Atlantic/Madeira",
  [TimeZones["Atlantic/Reykjavik"]]: "Atlantic/Reykjavik",
  [TimeZones["Atlantic/South_Georgia"]]: "Atlantic/South_Georgia",
  [TimeZones["Atlantic/St_Helena"]]: "Atlantic/St_Helena",
  [TimeZones["Atlantic/Stanley"]]: "Atlantic/Stanley",
  [TimeZones["Australia/Adelaide"]]: "Australia/Adelaide",
  [TimeZones["Australia/Brisbane"]]: "Australia/Brisbane",
  [TimeZones["Australia/Broken_Hill"]]: "Australia/Broken_Hill",
  [TimeZones["Australia/Currie"]]: "Australia/Currie",
  [TimeZones["Australia/Darwin"]]: "Australia/Darwin",
  [TimeZones["Australia/Eucla"]]: "Australia/Eucla",
  [TimeZones["Australia/Hobart"]]: "Australia/Hobart",
  [TimeZones["Australia/Lindeman"]]: "Australia/Lindeman",
  [TimeZones["Australia/Lord_Howe"]]: "Australia/Lord_Howe",
  [TimeZones["Australia/Melbourne"]]: "Australia/Melbourne",
  [TimeZones["Australia/Perth"]]: "Australia/Perth",
  [TimeZones["Australia/Sydney"]]: "Australia/Sydney",
  [TimeZones["Europe/Amsterdam"]]: "Europe/Amsterdam",
  [TimeZones["Europe/Andorra"]]: "Europe/Andorra",
  [TimeZones["Europe/Astrakhan"]]: "Europe/Astrakhan",
  [TimeZones["Europe/Athens"]]: "Europe/Athens",
  [TimeZones["Europe/Belgrade"]]: "Europe/Belgrade",
  [TimeZones["Europe/Berlin"]]: "Europe/Berlin",
  [TimeZones["Europe/Bratislava"]]: "Europe/Bratislava",
  [TimeZones["Europe/Brussels"]]: "Europe/Brussels",
  [TimeZones["Europe/Bucharest"]]: "Europe/Bucharest",
  [TimeZones["Europe/Budapest"]]: "Europe/Budapest",
  [TimeZones["Europe/Busingen"]]: "Europe/Busingen",
  [TimeZones["Europe/Chisinau"]]: "Europe/Chisinau",
  [TimeZones["Europe/Copenhagen"]]: "Europe/Copenhagen",
  [TimeZones["Europe/Dublin"]]: "Europe/Dublin",
  [TimeZones["Europe/Gibraltar"]]: "Europe/Gibraltar",
  [TimeZones["Europe/Guernsey"]]: "Europe/Guernsey",
  [TimeZones["Europe/Helsinki"]]: "Europe/Helsinki",
  [TimeZones["Europe/Isle_of_Man"]]: "Europe/Isle_of_Man",
  [TimeZones["Europe/Istanbul"]]: "Europe/Istanbul",
  [TimeZones["Europe/Jersey"]]: "Europe/Jersey",
  [TimeZones["Europe/Kaliningrad"]]: "Europe/Kaliningrad",
  [TimeZones["Europe/Kiev"]]: "Europe/Kiev",
  [TimeZones["Europe/Kirov"]]: "Europe/Kirov",
  [TimeZones["Europe/Lisbon"]]: "Europe/Lisbon",
  [TimeZones["Europe/Ljubljana"]]: "Europe/Ljubljana",
  [TimeZones["Europe/London"]]: "Europe/London",
  [TimeZones["Europe/Luxembourg"]]: "Europe/Luxembourg",
  [TimeZones["Europe/Madrid"]]: "Europe/Madrid",
  [TimeZones["Europe/Malta"]]: "Europe/Malta",
  [TimeZones["Europe/Mariehamn"]]: "Europe/Mariehamn",
  [TimeZones["Europe/Minsk"]]: "Europe/Minsk",
  [TimeZones["Europe/Monaco"]]: "Europe/Monaco",
  [TimeZones["Europe/Moscow"]]: "Europe/Moscow",
  [TimeZones["Europe/Oslo"]]: "Europe/Oslo",
  [TimeZones["Europe/Paris"]]: "Europe/Paris",
  [TimeZones["Europe/Podgorica"]]: "Europe/Podgorica",
  [TimeZones["Europe/Prague"]]: "Europe/Prague",
  [TimeZones["Europe/Riga"]]: "Europe/Riga",
  [TimeZones["Europe/Rome"]]: "Europe/Rome",
  [TimeZones["Europe/Samara"]]: "Europe/Samara",
  [TimeZones["Europe/San_Marino"]]: "Europe/San_Marino",
  [TimeZones["Europe/Sarajevo"]]: "Europe/Sarajevo",
  [TimeZones["Europe/Saratov"]]: "Europe/Saratov",
  [TimeZones["Europe/Simferopol"]]: "Europe/Simferopol",
  [TimeZones["Europe/Skopje"]]: "Europe/Skopje",
  [TimeZones["Europe/Sofia"]]: "Europe/Sofia",
  [TimeZones["Europe/Stockholm"]]: "Europe/Stockholm",
  [TimeZones["Europe/Tallinn"]]: "Europe/Tallinn",
  [TimeZones["Europe/Tirane"]]: "Europe/Tirane",
  [TimeZones["Europe/Ulyanovsk"]]: "Europe/Ulyanovsk",
  [TimeZones["Europe/Uzhgorod"]]: "Europe/Uzhgorod",
  [TimeZones["Europe/Vaduz"]]: "Europe/Vaduz",
  [TimeZones["Europe/Vatican"]]: "Europe/Vatican",
  [TimeZones["Europe/Vienna"]]: "Europe/Vienna",
  [TimeZones["Europe/Vilnius"]]: "Europe/Vilnius",
  [TimeZones["Europe/Volgograd"]]: "Europe/Volgograd",
  [TimeZones["Europe/Warsaw"]]: "Europe/Warsaw",
  [TimeZones["Europe/Zagreb"]]: "Europe/Zagreb",
  [TimeZones["Europe/Zaporozhye"]]: "Europe/Zaporozhye",
  [TimeZones["Europe/Zurich"]]: "Europe/Zurich",
  [TimeZones["Indian/Antananarivo"]]: "Indian/Antananarivo",
  [TimeZones["Indian/Chagos"]]: "Indian/Chagos",
  [TimeZones["Indian/Christmas"]]: "Indian/Christmas",
  [TimeZones["Indian/Cocos"]]: "Indian/Cocos",
  [TimeZones["Indian/Comoro"]]: "Indian/Comoro",
  [TimeZones["Indian/Kerguelen"]]: "Indian/Kerguelen",
  [TimeZones["Indian/Mahe"]]: "Indian/Mahe",
  [TimeZones["Indian/Maldives"]]: "Indian/Maldives",
  [TimeZones["Indian/Mauritius"]]: "Indian/Mauritius",
  [TimeZones["Indian/Mayotte"]]: "Indian/Mayotte",
  [TimeZones["Indian/Reunion"]]: "Indian/Reunion",
  [TimeZones["Pacific/Apia"]]: "Pacific/Apia",
  [TimeZones["Pacific/Auckland"]]: "Pacific/Auckland",
  [TimeZones["Pacific/Bougainville"]]: "Pacific/Bougainville",
  [TimeZones["Pacific/Chatham"]]: "Pacific/Chatham",
  [TimeZones["Pacific/Easter"]]: "Pacific/Easter",
  [TimeZones["Pacific/Efate"]]: "Pacific/Efate",
  [TimeZones["Pacific/Enderbury"]]: "Pacific/Enderbury",
  [TimeZones["Pacific/Fakaofo"]]: "Pacific/Fakaofo",
  [TimeZones["Pacific/Fiji"]]: "Pacific/Fiji",
  [TimeZones["Pacific/Funafuti"]]: "Pacific/Funafuti",
  [TimeZones["Pacific/Galapagos"]]: "Pacific/Galapagos",
  [TimeZones["Pacific/Gambier"]]: "Pacific/Gambier",
  [TimeZones["Pacific/Guadalcanal"]]: "Pacific/Guadalcanal",
  [TimeZones["Pacific/Guam"]]: "Pacific/Guam",
  [TimeZones["Pacific/Honolulu"]]: "Pacific/Honolulu",
  [TimeZones["Pacific/Johnston"]]: "Pacific/Johnston",
  [TimeZones["Pacific/Kiritimati"]]: "Pacific/Kiritimati",
  [TimeZones["Pacific/Kosrae"]]: "Pacific/Kosrae",
  [TimeZones["Pacific/Kwajalein"]]: "Pacific/Kwajalein",
  [TimeZones["Pacific/Majuro"]]: "Pacific/Majuro",
  [TimeZones["Pacific/Marquesas"]]: "Pacific/Marquesas",
  [TimeZones["Pacific/Midway"]]: "Pacific/Midway",
  [TimeZones["Pacific/Nauru"]]: "Pacific/Nauru",
  [TimeZones["Pacific/Niue"]]: "Pacific/Niue",
  [TimeZones["Pacific/Norfolk"]]: "Pacific/Norfolk",
  [TimeZones["Pacific/Noumea"]]: "Pacific/Noumea",
  [TimeZones["Pacific/Pago_Pago"]]: "Pacific/Pago_Pago",
  [TimeZones["Pacific/Palau"]]: "Pacific/Palau",
  [TimeZones["Pacific/Pitcairn"]]: "Pacific/Pitcairn",
  [TimeZones["Pacific/Ponape"]]: "Pacific/Ponape",
  [TimeZones["Pacific/Port_Moresby"]]: "Pacific/Port_Moresby",
  [TimeZones["Pacific/Rarotonga"]]: "Pacific/Rarotonga",
  [TimeZones["Pacific/Saipan"]]: "Pacific/Saipan",
  [TimeZones["Pacific/Tahiti"]]: "Pacific/Tahiti",
  [TimeZones["Pacific/Tarawa"]]: "Pacific/Tarawa",
  [TimeZones["Pacific/Tongatapu"]]: "Pacific/Tongatapu",
  [TimeZones["Pacific/Truk"]]: "Pacific/Truk",
  [TimeZones["Pacific/Wake"]]: "Pacific/Wake",
  [TimeZones["Pacific/Wallis"]]: "Pacific/Wallis",
}
