// apps/web/app/layout.tsx
import "./globals.css";
import "@repo/frontend/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppLayout } from "../components/appLayout/AppLayout";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}>
          <AppLayout>{children}</AppLayout>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
